/**
 * Shop Analytics API
 * API for retrieving shop analytics data including income, expenses, and revenue.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DayAnalyticsDto { 
    date?: string;
    income?: number;
    outcome?: number;
    revenue?: number;
}