/*
 * Shop Analytics API
 *
 * API for retrieving shop analytics data including income, expenses, and revenue.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using ShopAnalytics.Api.Analytics.GetAnalytics;
using ShopAnalytics.Attributes;
using ShopAnalytics.Models;
using Swashbuckle.AspNetCore.Annotations;

namespace ShopAnalytics.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class AnalyticsApiController(IMediator mediator) : AppBaseController
    {
        /// <summary>
        /// Get shop analytics
        /// </summary>
        /// <remarks>Retrieves income, outcome, and revenue analytics for a given date range.</remarks>
        /// <param name="shopId">The ID of the shop to retrieve analytics for.</param>
        /// <param name="fromDate">The start date for analytics retrieval (YYYY-MM-DD).</param>
        /// <param name="toDate">The end date for analytics retrieval (YYYY-MM-DD).</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <response code="200">Daily analytics data.</response>
        [HttpGet]
        [Route("/analytics")]
        [ValidateModelState]
        [SwaggerOperation("GetAnalytics")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<DayAnalyticsDto>), description: "Daily analytics data.")]
        public virtual async Task<IActionResult> GetAnalytics([FromQuery] [Required()] Guid shopId,
            [FromQuery] [Required()] DateTime fromDate, [FromQuery] [Required()] DateTime toDate,
            CancellationToken cancellationToken)
        {
            return ResultOf(await mediator.Send(new GetAnalyticsQuery(shopId, fromDate, toDate), cancellationToken));
        }
    }

}
