/*
 * Shop Analytics API
 *
 * API for retrieving shop analytics data including income, expenses, and revenue.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using MediatR;
using Microsoft.AspNetCore.Mvc;
using ShopAnalytics.Api.Shop.GetShops;
using ShopAnalytics.Attributes;
using ShopAnalytics.Models;
using Swashbuckle.AspNetCore.Annotations;

namespace ShopAnalytics.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ShopsApiController(IMediator mediator) : AppBaseController
    { 
        /// <summary>
        /// Get all shops
        /// </summary>
        /// <remarks>Retrieves a list of all available shops.</remarks>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <response code="200">A list of shops.</response>
        [HttpGet]
        [Route("/shops")]
        [ValidateModelState]
        [SwaggerOperation("GetShops")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<ShopDto>), description: "A list of shops.")]
        public virtual async Task<IActionResult> GetShops(CancellationToken cancellationToken)
        { 
            return ResultOf(await mediator.Send(new GetShopsQuery(), cancellationToken));
        }
    }
}
