services:
  backend:
    build:
      context: .
      dockerfile: ShopAnalytics/ShopAnalytics/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./ShopAnalyticsClient
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "4200:443"
    depends_on:
      - backend
