version: '3.8'

services:
  backend:
    build:
      context: ./ShopAnalytics/ShopAnalytics
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./ShopAnalyticsClient
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend